repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-case-conflict
        name: pre-commit-hooks - Check for case conflicts
      - id: trailing-whitespace
        name: pre-commit-hooks - Trim Trailing Whitespace
      - id: end-of-file-fixer
        name: pre-commit-hooks - Fix End of Files
      - id: check-docstring-first
        name: pre-commit-hooks - Checks for a common error of placing code before the docstring
      - id: check-executables-have-shebangs
        name: pre-commit-hooks - Checks that non-binary executables have a proper shebang
      - id: name-tests-test
        name: pre-commit-hooks - Tests should end in _test.py
      - id: requirements-txt-fixer
        name: pre-commit-hooks - Fix requirements.txt

  - repo: local
    hooks:
      - id: isort
        name: python - isort
        stages: [commit]
        language: system
        entry: isort
        types: [python]
      - id: black
        name: python - black
        stages: [commit]
        language: system
        entry: black
        types: [python]
      - id: flake8
        name: python - flake8
        stages: [commit]
        language: system
        entry: flake8
        types: [python]
      - id: pylint
        name: python - pylint
        stages: [commit]
        language: system
        entry: pylint
        types: [python]
      - id: pydocstyle
        name: python - pydocstyle
        stages: [commit]
        language: system
        entry: pydocstyle
        types: [python]
      - id: prospector
        name: python - prospector
        stages: [commit]
        language: system
        entry: prospector
        types: [python]
      - id: pytype
        name: python - pytype
        stages: [commit]
        language: system
        entry: pytype
        types: [python]
